### ISSUE TITLE
Problems I found in FrozenLake

### ISSUE THREAD

**Issue by lukewys** [simoninithomas/Deep_reinforcement_learning_Course#6]
I found that there is a high chance I would get all-zero Q-table after Q-learning algorithm. After some google, I found that the environment  FrozenLake is default to be "slippery", so you don't always go where you want. So I guess the agents just aren't lucky enough to random to the goal. And later on, the epsilon decreased, and the agents does less exploration. (Although due to "slippery" environment, they could still see as doing random exploration.)  And though sometime it learned the Q-table, the action it decide is quite weird, (go left at the beginning for example), but it still have as much as 0.49 score over time. So I think it is largely "slipped" to the end.
So my solution is after the Q-learning process, if the Q-table is still all-zero, I would reset the epsilon as 1 and start the iteration again. Also, reducing the decay_rate helps as well.
Last, I found a way to close the "is_slippery" option:

from gym.envs.registration import register
register(
    id='FrozenLakeNotSlippery-v0',
    entry_point='gym.envs.toy_text:FrozenLakeEnv',
    kwargs={'map_name' : '4x4', 'is_slippery': False},
    max_episode_steps=100,
    reward_threshold=0.78, # optimum = .8196
)
env = gym.make("FrozenLakeNotSlippery-v0")

from https://github.com/openai/gym/issues/565

**Comment by simoninithomas** [comment]
Hi,
Thanks for your contribution, I didn't know why there was this bug from time to time.
The goal is to keep slippery in our game (because the tutorial is made with slippery in mind). But I will add your contribution and credit you in a "non-slipery notebook version".
Again thanks for your finding that's awesome !

**Comment by simoninithomas** [comment]
Hi,

I removed my first message because there was a mistake,

Thanks for your contribution, but I've just tested with your non-slippery version and I have 0.0001 score after the training.

If you have a working version you can make a pull request and we'll put it on the repository with your name credited in it.

However, we'll keep the slippery version for the tutorial because we work in a stochastic environment and here by deleting slippery you've made an deterministic environment. But if you want we'll put this version on the repo too.

Again awesome work!

**Comment by lukewys** [comment]
Thanks for the reply!
Yes I find that a relatively small decay_rate is very useful to improve the chance of success.
I don't quite know how to pull the request, so I just attach the file here.
Also I changed the decay_rate to 0.001. It work much better with a small decay_rate.

[Q Learning with FrozenLake_unslippery.zip](https://github.com/simoninithomas/Deep_reinforcement_learning_Course/files/2282736/Q.Learning.with.FrozenLake_unslippery.zip)
